logging:
  pattern:
    console: "%d - %msg%n" #     定义打印的日志格式
    #    dateformat: #设置日志日期格式
    #    file: #定义输出到日志文件的日志格式
    #  config: #日志配置文件的位置。例如，classpath:logback.xml。
    file: D:/gmall/gmall-manage.log #设置保存日志的日志文件
    #    max-history:
    #    max-size: #设置日志文件最大大小 #设置日志等级
    #  path: / #日志文件的位置，例如/var/log
    register-shutdown-hook: false #当初始化日志系统时，为其注册一个关闭钩子。
    level: info
spring:
  application:
    name: GMALL-MANAGE
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.130.128
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    prefer-ip-address: true
server:
  port: 8088
