spring:
  application:
    name: GMALL-MANAGEUI
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8081